/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedReturnsRouteImport } from './routes/_authenticated/returns'
import { Route as AuthenticatedShopifyRouteImport } from './routes/_authenticated/shopify'
import { Route as AuthenticatedSummaryRouteImport } from './routes/_authenticated/summary'
import { Route as ApiPublicShopifyWebhookRouteImport } from './routes/api/public/shopify-webhook'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReturnsRoute = AuthenticatedReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShopifyRoute = AuthenticatedShopifyRouteImport.update({
  id: '/shopify',
  path: '/shopify',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSummaryRoute = AuthenticatedSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicShopifyWebhookRoute = ApiPublicShopifyWebhookRouteImport.update({
  id: '/api/public/shopify-webhook',
  path: '/api/public/shopify-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/shopify': typeof AuthenticatedShopifyRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/returns': typeof AuthenticatedReturnsRoute
  '/shopify': typeof AuthenticatedShopifyRoute
  '/summary': typeof AuthenticatedSummaryRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/returns': typeof AuthenticatedReturnsRoute
  '/_authenticated/shopify': typeof AuthenticatedShopifyRoute
  '/_authenticated/summary': typeof AuthenticatedSummaryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/shopify-webhook': typeof ApiPublicShopifyWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/expenses'
    | '/orders'
    | '/returns'
    | '/shopify'
    | '/summary'
    | '/api/public/shopify-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/expenses'
    | '/orders'
    | '/returns'
    | '/shopify'
    | '/summary'
    | '/'
    | '/api/public/shopify-webhook'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/expenses'
    | '/_authenticated/orders'
    | '/_authenticated/returns'
    | '/_authenticated/shopify'
    | '/_authenticated/summary'
    | '/_authenticated/'
    | '/api/public/shopify-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicShopifyWebhookRoute: typeof ApiPublicShopifyWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/returns': {
      id: '/_authenticated/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AuthenticatedReturnsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shopify': {
      id: '/_authenticated/shopify'
      path: '/shopify'
      fullPath: '/shopify'
      preLoaderRoute: typeof AuthenticatedShopifyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/summary': {
      id: '/_authenticated/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof AuthenticatedSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/shopify-webhook': {
      id: '/api/public/shopify-webhook'
      path: '/api/public/shopify-webhook'
      fullPath: '/api/public/shopify-webhook'
      preLoaderRoute: typeof ApiPublicShopifyWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedReturnsRoute: typeof AuthenticatedReturnsRoute
  AuthenticatedShopifyRoute: typeof AuthenticatedShopifyRoute
  AuthenticatedSummaryRoute: typeof AuthenticatedSummaryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedReturnsRoute: AuthenticatedReturnsRoute,
  AuthenticatedShopifyRoute: AuthenticatedShopifyRoute,
  AuthenticatedSummaryRoute: AuthenticatedSummaryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicShopifyWebhookRoute: ApiPublicShopifyWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
